### ISSUE TITLE
Banners for Learning Journey

### ISSUE THREAD

**Issue by brian-murray35** [brian-murray35/Learning_Journey#12]
EPIC number: 
 
As a _user_,  I want to _a banner on each learning journey_ so that I can _easily view information about the learning journey I'm currently on, and also to navigate to **related learning journeys** or **all learning journeys**_.

Description

This Epic provide high level information about the different types of banners for the Learning Journey page. This epic contains the following stories:
- [ ] Create and display bright banner
- [ ] Create and display dark banner
- [ ] Enable toggle between the two banners (depends on LJ is displayed)

Design
Bright 
![image](https://user-images.githubusercontent.com/8071467/29521393-41766a3c-867d-11e7-9821-7128ea675ead.png)

Dark 
![image](https://user-images.githubusercontent.com/8071467/29521358-14ded626-867d-11e7-9202-a6619b0e2918.png)

Interaction

_Functional Flow 1_

1. User selects a learning journey on the Learning Journey home page (on either the Learning Hub or the Help Portal)

### Acceptance Criteria

Topic 1

1. Cre

### Tasks

- [ ] Task 1
- [ ] Task 1
- [ ] Task 1
- [ ] Task 1
- [ ] Task 1
---

### "Ready Criteria" Check

- [ ] Functional Requirement Ready
- [ ] Design Ready
- [ ] Technical Elaboration Ready
- [ ] Estimated Size under 1 Sprint
- [ ] The impacted modules have been defined
- [ ] Dependencies defined and described
- [ ] Favors the reuse of existing OS components
- [ ] Testability and deployability constraints are taken into account 
- [ ] Deployability validated and approved
- [ ] Migration Assessment

---

### "Done Criteria" Check
 
- [ ] QE Acceptance
- [ ] PM Acceptance
- [ ] UX Acceptance
- [ ] Technical Implementation Review/Acceptance
- [ ] Technical Architecture Review/Acceptance
- [ ] Needs to Run, Demo & Test on Central Landscape
- [ ] Deployability
- [ ] 3rd Party Needs reported to Vidya
- [ ] Feature tested on system with migrated previous version tenant database
- [ ] Automated Test in place (unit/API)
- [ ] Externalization of new strings
- [ ] Migration code implemented
- [ ] Statistics Tracking
- [ ] Feature Toggle
- [ ] GTP Test Case linked

---
